export const EDIT_USER_PROFILE_REQUEST = Symbol('users/EDIT_USER_PROFILE_REQUEST');
export const EDIT_USER_PROFILE_SUCCESS = Symbol('users/EDIT_USER_PROFILE_SUCCESS');
export const EDIT_USER_PROFILE_FAILURE = Symbol('users/EDIT_USER_PROFILE_FAILURE');
